before:
  hooks:
    - go mod tidy

builds:
  - binary: bin/tifling
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"
    ldflags:
      - -X main.Version=={{.Version}}
